fir_todos/urls.py
from django.conf.urls import patterns, url

from fir_todos import views

urlpatterns = patterns('',
	url(r'^(?P<incident_id>\d+)/list/$', views.list, name='list'),
	url(r'^(?P<incident_id>\d+)/create/$', views.create, name='create'),
	url(r'^(?P<todo_id>\d+)/delete/$', views.delete, name='delete'),
	url(r'^(?P<todo_id>\d+)/toggle_status/$', views.toggle_status, name='toggle_status'),
	url(r'^tasks/$', views.dashboard, name='dashboard'),
)

incidents/urls.py
from django.conf.urls import patterns, url

from incidents import views

urlpatterns = patterns('',
    url(r'^$', views.index,  { 'is_incident': True }, name='index'),
    url(r'^all/$', views.incidents_all, name='all'),
    url(r'^(?P<incident_id>\d+)/$', views.details, name='details'),
    url(r'^(?P<incident_id>\d+)/followup/$', views.followup, name='followup'),
    url(r'^(?P<incident_id>\d+)/comment/$', views.comment, name='comment'),
    url(r'^(?P<incident_id>\d+)/upload/$', views.upload_file, name='upload_file'),
    url(r'^(?P<incident_id>\d+)/comment/(?P<comment_id>\d+)/delete/$', views.delete_comment, name='delete_comment'),
    url(r'^(?P<incident_id>\d+)/edit/$', views.edit_incident, name='edit'),
    url(r'^(?P<incident_id>\d+)/delete/$', views.delete_incident, name='delete'),
    url(r'^(?P<incident_id>\d+)/download/(?P<filename>.+)$', views.download, name='download'),
    url(r'^(?P<incident_id>\d+)/download/$', views.download_archive, name='download_archive'),
    url(r'^(?P<incident_id>\d+)/remove/(?P<file_id>\d+)$', views.remove_file, name='remove_file'),
    url(r'^(?P<incident_id>\d+)/status/(?P<status>[OBC])$', views.change_status, name='change_status'),
    url(r'^(?P<incident_id>\d+)/attribute$', views.add_attribute, name='add_attribute'),
    url(r'^(?P<incident_id>\d+)/attribute/(?P<attribute_id>\d+)/delete/$', views.delete_attribute, name='delete_attribute'),
)

incidents/models.py
# -*- coding: utf-8 -*-
import os
import datetime
import hashlib

from django.db import models
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User

from fir_artifacts import artifacts

STATUS_CHOICES = (
	("O", "Open"),
	("C", "Closed"),
	("B", "Blocked"),
	)

SEVERITY_CHOICES = (
	(1, '1'),
	(2, '2'),
	(3, '3'),
	(4, '4'),
	)

LOG_ACTIONS = (
	("D", "Deleted"),
	("C", "Created"),
	("U", "Update"),
	("LI", "Logged in"),
	("LO", "Logged out"),
	)

CONFIDENTIALITY_LEVEL = (
	(0, "C0"),
	(1, "C1"),
	(2, "C2"),
	(3, "C3"),
	)

# Profile ====================================================================


class Profile(models.Model):
	user = models.OneToOneField(User)
	incident_number = models.IntegerField(default=50)
	hide_closed = models.BooleanField(default=False)

	def __unicode__(self):
		return u"Profile for user '{}'".format(self.user)

# Audit trail ================================================================


class Log(models.Model):
	who = models.ForeignKey(User)
	what = models.CharField(max_length=100, choices=STATUS_CHOICES)
	when = models.DateTimeField(auto_now_add=True)
	incident = models.ForeignKey('Incident', null=True, blank=True)
	comment = models.ForeignKey('Comments', null=True, blank=True)

	def __unicode__(self):
		if self.incident:
			return u"[%s] %s %s (%s)" % (self.when, self.what, self.incident, self.who)
		elif self.comment:
			return u"[%s] %s comment on %s (%s)" % (self.when, self.what, self.comment.incident, self.who)
		else:
			return u"[%s] %s (%s)" % (self.when, self.what, self.who)


class LabelGroup(models.Model):
	name = models.CharField(max_length=50)

	def __unicode__(self):
		return self.name


class Label(models.Model):
	name = models.CharField(max_length=50)
	group = models.ForeignKey(LabelGroup)

	def __unicode__(self):
		return "%s" % (self.name)

def upload_path(instance, filename):
	return "%s/%s" % (instance.incident.id, filename)

class File(models.Model):

	def getfilename(self):
		return os.path.basename(self.file.name)

	def get_hashes(self):
		hashes = dict((k, None) for k in ['md5', 'sha1', 'sha256'])
		content = self.file.read()
		for algo in hashes:
			m = hashlib.new(algo)
			m.update(content)
			hashes[algo] = m.hexdigest()
		return hashes

	hashes = models.ManyToManyField('Artifact', null=True, blank=True)
	description = models.CharField(max_length=256)
	file = models.FileField(upload_to=upload_path)
	incident = models.ForeignKey('Incident')
	date = models.DateTimeField(auto_now_add=True)


class BusinessLine(models.Model):
	name = models.CharField(max_length=100)
	parent = models.ForeignKey('BusinessLine', null=True, blank=True)

	def __unicode__(self):

		ret = [self.name]

		parent = self.parent
		while parent:
			ret.append(parent.name)
			parent = parent.parent

		ret.reverse()
		return u" > ".join(ret)

	class Meta:
		ordering = ["parent__name", "name"]

	def get_children(self):
		return BusinessLine.objects.filter(parent=self.id)

	def get_incident_count(self, query):
		incident_count = self.incident_set.filter(query).distinct().count()
		bls = BusinessLine.objects.filter(parent=self.id)

		while len(bls) > 0:
			incident_count += Incident.objects.filter(query).filter(concerned_business_lines__in=bls).distinct().count()
			bls = BusinessLine.objects.filter(parent__in=bls)

		return incident_count

	def get_top_parent(self):
		parent = self
		while parent.parent is not None:
			parent = parent.parent
		return parent

	@staticmethod
	def get_parents():
		return BusinessLine.objects.filter(parent=None)


class BaleCategory(models.Model):
	name = models.CharField(max_length=200)
	description = models.TextField(blank=True, null=True)
	category_number = models.IntegerField()
	parent_category = models.ForeignKey('BaleCategory', null=True, blank=True)

	class Meta:
		verbose_name_plural = "Bale categories"

	def __unicode__(self):
		if self.parent_category:
			return "(%s > %s) %s" % (self.parent_category.category_number, self.category_number, self.name)
		else:
			return "(%s) %s" % (self.category_number, self.name)


class IncidentCategory(models.Model):
	name = models.CharField(max_length=100)
	bale_subcategory = models.ForeignKey(BaleCategory)
	is_major = models.BooleanField(default=False)

	class Meta:
		verbose_name_plural = "Incident categories"

	def __unicode__(self):
		return self.name

# Core models ================================================================


class Incident(models.Model):
	date = models.DateTimeField(default=datetime.datetime.now, blank=True)
	is_starred = models.BooleanField(default=False)
	subject = models.CharField(max_length=256)
	description = models.TextField()
	category = models.ForeignKey(IncidentCategory)
	concerned_business_lines = models.ManyToManyField(BusinessLine, null=True, blank=True)
	main_business_lines = models.ManyToManyField(BusinessLine, related_name='incidents_affecting_main', null=True, blank=True)
	detection = models.ForeignKey(Label, limit_choices_to={'group__name': 'detection'}, related_name='detection_label')
	severity = models.IntegerField(choices=SEVERITY_CHOICES)
	is_incident = models.BooleanField(default=False)
	is_major = models.BooleanField(default=False)
	actor = models.ForeignKey(Label, limit_choices_to={'group__name': 'actor'}, related_name='actor_label', blank=True, null=True)
	plan = models.ForeignKey(Label, limit_choices_to={'group__name': 'plan'}, related_name='plan_label', blank=True, null=True)
	status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="Open")
	opened_by = models.ForeignKey(User)
	confidentiality = models.IntegerField(choices=CONFIDENTIALITY_LEVEL, default='1')

	def __unicode__(self):
		return self.subject

	def is_open(self):
		return self.get_last_action != "Closed"

	def close_timeout(self):
		self.status = 'C'
		self.save()

		c = Comments()
		c.comment = "Incident closed (timeout)"
		c.date = datetime.datetime.now()
		c.action = Label.objects.get(name='Closed', group__name='action')
		c.incident = self
		c.opened_by = User.objects.get(username='cert')
		c.save()

	def get_last_comment(self):
		return self.comments_set.order_by('-date')[0]

	def get_last_action(self):
		c = self.comments_set.order_by('-date')[0]

		action = "%s (%s)" % (c.action, c.date.strftime("%Y %d %b %H:%M:%S"))

		return action

	def concerns_business_line(self, bl_string):
		for bl in self.concerned_business_lines.all():
			if bl.name == bl_string:
				return True

			parent = bl.parent
			while parent:
				if parent.name == bl_string:
					return True
				parent = parent.parent

		return False

	def get_business_lines_names(self):
		return ", ".join([b.name for b in self.concerned_business_lines.all()])

	def refresh_main_business_lines(self):
		mainbls = set()
		for bl in self.concerned_business_lines.all():
			mainbls.add(bl.get_top_parent())
		self.main_business_lines = list(mainbls)

	def refresh_artifacts(self, data=""):
		if data == "":
			coms = self.comments_set.all()

			data = self.description
			for c in coms:
				data += "\n" + c.comment

		found_artifacts = artifacts.find(data)

		artifact_list = []
		for key in found_artifacts:
			for a in found_artifacts[key]:
				artifact_list.append((key, a))

		db_artifacts = Artifact.objects.filter(value__in=[a[1] for a in artifact_list])

		exist = []

		for a in db_artifacts:
			exist.append((a.type, a.value))
			if self not in a.incidents.all():
				a.incidents.add(self)

		new_artifacts = list(set(artifact_list) - set(exist))
		all_artifacts = list(set(artifact_list))

		for a in new_artifacts:
			new = Artifact(type=a[0], value=a[1])
			new.save()
			new.incidents.add(self)

		for a in all_artifacts:
			artifacts.after_save(a[0], a[1], self)

	class Meta:
		permissions = (
			('handle_incidents', 'Can handle incidents'),
			('view_statistics', 'Can view statistics'),
		)


class Comments(models.Model):
	date = models.DateTimeField(default=datetime.datetime.now, blank=True)
	comment = models.TextField()
	action = models.ForeignKey(Label, limit_choices_to={'group__name': 'action'}, related_name='action_label')
	incident = models.ForeignKey(Incident)
	opened_by = models.ForeignKey(User)

	def __unicode__(self):
		return u"Comment for incident %s" % self.incident.id


class Artifact(models.Model):
	type = models.CharField(max_length=20)
	value = models.CharField(max_length=200)
	incidents = models.ManyToManyField(Incident)

	def __unicode__(self):
		display = self.value
		if self.incidents.count() > 1:
			display += " (%s)" % self.incidents.count()
		return display


class Attribute(models.Model):
	name = models.CharField(max_length=50)
	value = models.CharField(max_length=200)
	incident = models.ForeignKey(Incident)

	def __unicode__(self):
		return "%s: %s" % (self.name, self.value)


class ValidAttribute(models.Model):
	name = models.CharField(max_length=50)
	unit = models.CharField(max_length=50, null=True, blank=True)
	description = models.CharField(max_length=500, null=True, blank=True)
	categories = models.ManyToManyField(IncidentCategory)

	def __unicode__(self):
		return self.name

# forms ===============================================================


class IncidentForm(ModelForm):

	def __init__(self, *args, **kwargs):
		super(ModelForm, self).__init__(*args, **kwargs)
		self.fields['subject'].error_messages['required'] = 'This field is required.'
		self.fields['category'].error_messages['required'] = 'This field is required.'
		self.fields['concerned_business_lines'].error_messages['required'] = 'This field is required.'
		self.fields['detection'].error_messages['required'] = 'This field is required.'

		self.fields['severity'].error_messages['required'] = 'This field is required.'
		self.fields['is_major'].error_messages['required'] = 'This field is required.'

		self.fields['is_major'].label = 'Major?'

	class Meta:
		model = Incident
		exclude = ('opened_by', 'main_business_lines', 'is_starred')


class CommentForm(ModelForm):

incidents/templates/incidents/followup.html
{% load fir_plugins %}

<html lang="en">
<head>
	<link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/custom_css/fir_followup.css" rel="stylesheet">
    {% plugin_point 'followup_static' %}
    <title>{% if incident.is_incident %}Incident{%else%}Event{%endif%} followup [C{{incident.confidentiality}}] [{{incident.category}}] - {{incident.subject}}</title>
</head>
<body>
	<div class='frame'>

		<div class='header'>
			<img src='{{ STATIC_URL }}img/logo.jpg' />
			<br style='clear:both' />
			<div class='title'>
				<h1 class='float'>{% if incident.is_incident %}Incident{%else%}Event{%endif%} followup [C{{incident.confidentiality}}] [{{incident.category}}] - {{incident.subject}}</h1>
				<br style='clear:both' />
				<p>Opened on {{ incident.date }} by {{ incident.opened_by|default:"someone"}}</p>
			</div>
		</div>


		<table class='minitable table'>
			<tr class='slim'>
				{%if incident.is_incident%}
				<td class='head'>Incident Leader</td><td class='delim'>{{ incident.actor }}</td>
				<td class='head'>Plan</td><td class='delim'>{{ incident.plan }}</td>
				{%endif%}
				<td class='head'>Severity</td><td class='delim'>{{ incident.severity }}</td>
				<td class='head'>Category</td><td class='delim'>{{ incident.category }}</td>
				<td class='head'>Status</td><td class='delim'><span class='label {%if incident.status == "B"%}label-danger{%endif%}{%if incident.status == "C"%}label-info{%endif%}'>{{ incident.get_status_display}}</span></td>

				<td class='head'>Detection</td><td class='delim'>{{ incident.detection }}</td>
				<td class='head'>B/L</td><td>{{ incident.get_business_lines_names }}</td>
			</tr>
		</table>


		<br style='clear:both' />


		<div class='description'>
			<h3>Summary</h3>
			<p class='artifacts'>{{ incident.description|safe }}</p>
		</div>

		<br style='clear:both' />

		<h2>Incident timeline ({{ incident.comments_set.count }})</h2>

		<table class="table table-hover table-condensed">
			<thead>
				<tr>
					<th style='width:20%'>Date</th>
					<th>Author</th>
					<th>Comment</th>
					<th>Action</th>
				</tr>
			</thead>
		{% for comment in comments.all %}
		  <tr id="comment_id_{{comment.id}}">
		  	<td style='width:10%'>{{ comment.date|date:"Y-m-d G:i" }}</td>
		  	<td>{{ comment.opened_by|default:"someone" }}</td>
		  	<td class='artifacts'>{{ comment.comment|safe }}</td>
		  	<td>{{ comment.action }}</td>
		  </tr>
		{% endfor %}

		</table>

		{% plugin_point 'followup_main' %}

		<div class='files'>

			<h2>Related files</h2>
			<br style='clear:both'/>
			{%if incident.file_set.count > 0 %}
				<table class='table table-condensed files' style='width:auto'>
					{% for file in incident.file_set.all %}
						<tr>
							<td >{{file.date|date:"d-m-Y"}}</td>
							<td>{{ file.getfilename }}</td>
							<td>{{ file.description }}</td>
						</tr>
					{%endfor%}
				</table>
			{% else %}
				No files for this incident.
			{% endif %}
		</div>
	</div>

</body>
</html>

incidents/templates/incidents/login.html
{% load url from future %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Sign in &middot; FIR</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/custom_css/fir.css" rel="stylesheet">
    <link href="/static/custom_css/login.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="/static/js/html5.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="shortcut icon" href="/static/img/favicon.png">
  </head>

  <body>

    <div class="container">
      <div class="col-sm-4 col-sm-offset-4 col-xs-12 col-xs-offset-0">
        <form class="form-signin" method="post">
          <img class="img-responsive" src="/static/img/logo.jpg" alt="Logo" />

          {% csrf_token %}

          <h2 class="form-signin-heading">Sign in to FIR</h2>

          <div class="form-group">
            <input type="text" class="form-control" placeholder="Username" name="username" />
          </div>
          <div class="form-group">
            <input type="password" class="form-control" placeholder="Password" name="password" />
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox" value="remember-me" name="remember"> Remember me
            </label>
          </div>
          <button class="btn btn-large btn-primary" type="submit">Sign in</button>
        </form>

        {% if error %}
          <div class="alert alert-warning alert-dismissible" id="error">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>Wrong username / password combination.</strong><br/>I can break the rules, too.
          </div>
        {% endif %}
      </div>
    </div>

    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
  </body>
</html>