fir_todos/urls.py
from django.conf.urls import patterns, url

from fir_todos import views

urlpatterns = patterns('',
	url(r'^(?P<incident_id>\d+)/list/$', views.list, name='list'),
	url(r'^(?P<incident_id>\d+)/create/$', views.create, name='create'),
	url(r'^(?P<todo_id>\d+)/delete/$', views.delete, name='delete'),
	url(r'^(?P<todo_id>\d+)/toggle_status/$', views.toggle_status, name='toggle_status'),
	url(r'^tasks/$', views.dashboard, name='dashboard'),
)

incidents/urls.py
from django.conf.urls import patterns, url

from incidents import views

urlpatterns = patterns('',
    url(r'^$', views.index,  { 'is_incident': True }, name='index'),
    url(r'^all/$', views.incidents_all, name='all'),
    url(r'^(?P<incident_id>\d+)/$', views.details, name='details'),
    url(r'^(?P<incident_id>\d+)/followup/$', views.followup, name='followup'),
    url(r'^(?P<incident_id>\d+)/comment/$', views.comment, name='comment'),
    url(r'^(?P<incident_id>\d+)/upload/$', views.upload_file, name='upload_file'),
    url(r'^(?P<incident_id>\d+)/comment/(?P<comment_id>\d+)/delete/$', views.delete_comment, name='delete_comment'),
    url(r'^(?P<incident_id>\d+)/edit/$', views.edit_incident, name='edit'),
    url(r'^(?P<incident_id>\d+)/delete/$', views.delete_incident, name='delete'),
    url(r'^(?P<incident_id>\d+)/download/(?P<filename>.+)$', views.download, name='download'),
    url(r'^(?P<incident_id>\d+)/download/$', views.download_archive, name='download_archive'),
    url(r'^(?P<incident_id>\d+)/remove/(?P<file_id>\d+)$', views.remove_file, name='remove_file'),
    url(r'^(?P<incident_id>\d+)/status/(?P<status>[OBC])$', views.change_status, name='change_status'),
    url(r'^(?P<incident_id>\d+)/attribute$', views.add_attribute, name='add_attribute'),
    url(r'^(?P<incident_id>\d+)/attribute/(?P<attribute_id>\d+)/delete/$', views.delete_attribute, name='delete_attribute'),
)

incidents/models.py
# -*- coding: utf-8 -*-
import os
import datetime
import hashlib

from django.db import models
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User

from fir_artifacts import artifacts

STATUS_CHOICES = (
	("O", "Open"),
	("C", "Closed"),
	("B", "Blocked"),
	)

SEVERITY_CHOICES = (
	(1, '1'),
	(2, '2'),
	(3, '3'),
	(4, '4'),
	)

LOG_ACTIONS = (
	("D", "Deleted"),
	("C", "Created"),
	("U", "Update"),
	("LI", "Logged in"),
	("LO", "Logged out"),
	)

CONFIDENTIALITY_LEVEL = (
	(0, "C0"),
	(1, "C1"),
	(2, "C2"),
	(3, "C3"),
	)

# Profile ====================================================================


class Profile(models.Model):
	user = models.OneToOneField(User)
	incident_number = models.IntegerField(default=50)
	hide_closed = models.BooleanField(default=False)

	def __unicode__(self):
		return u"Profile for user '{}'".format(self.user)

# Audit trail ================================================================


class Log(models.Model):
	who = models.ForeignKey(User)
	what = models.CharField(max_length=100, choices=STATUS_CHOICES)
	when = models.DateTimeField(auto_now_add=True)
	incident = models.ForeignKey('Incident', null=True, blank=True)
	comment = models.ForeignKey('Comments', null=True, blank=True)

	def __unicode__(self):
		if self.incident:
			return u"[%s] %s %s (%s)" % (self.when, self.what, self.incident, self.who)
		elif self.comment:
			return u"[%s] %s comment on %s (%s)" % (self.when, self.what, self.comment.incident, self.who)
		else:
			return u"[%s] %s (%s)" % (self.when, self.what, self.who)


class LabelGroup(models.Model):
	name = models.CharField(max_length=50)

	def __unicode__(self):
		return self.name


class Label(models.Model):
	name = models.CharField(max_length=50)
	group = models.ForeignKey(LabelGroup)

	def __unicode__(self):
		return "%s" % (self.name)

def upload_path(instance, filename):
	return "%s/%s" % (instance.incident.id, filename)

class File(models.Model):

	def getfilename(self):
		return os.path.basename(self.file.name)

	def get_hashes(self):
		hashes = dict((k, None) for k in ['md5', 'sha1', 'sha256'])
		content = self.file.read()
		for algo in hashes:
			m = hashlib.new(algo)
			m.update(content)
			hashes[algo] = m.hexdigest()
		return hashes

	hashes = models.ManyToManyField('Artifact', null=True, blank=True)
	description = models.CharField(max_length=256)
	file = models.FileField(upload_to=upload_path)
	incident = models.ForeignKey('Incident')
	date = models.DateTimeField(auto_now_add=True)


class BusinessLine(models.Model):
	name = models.CharField(max_length=100)
	parent = models.ForeignKey('BusinessLine', null=True, blank=True)

	def __unicode__(self):

		ret = [self.name]

		parent = self.parent
		while parent:
			ret.append(parent.name)
			parent = parent.parent

		ret.reverse()
		return u" > ".join(ret)

	class Meta:
		ordering = ["parent__name", "name"]

	def get_children(self):
		return BusinessLine.objects.filter(parent=self.id)

	def get_incident_count(self, query):
		incident_count = self.incident_set.filter(query).distinct().count()
		bls = BusinessLine.objects.filter(parent=self.id)

		while len(bls) > 0:
			incident_count += Incident.objects.filter(query).filter(concerned_business_lines__in=bls).distinct().count()
			bls = BusinessLine.objects.filter(parent__in=bls)

		return incident_count

	def get_top_parent(self):
		parent = self
		while parent.parent is not None:
			parent = parent.parent
		return parent

	@staticmethod
	def get_parents():
		return BusinessLine.objects.filter(parent=None)


class BaleCategory(models.Model):
	name = models.CharField(max_length=200)
	description = models.TextField(blank=True, null=True)
	category_number = models.IntegerField()
	parent_category = models.ForeignKey('BaleCategory', null=True, blank=True)

	class Meta:
		verbose_name_plural = "Bale categories"

	def __unicode__(self):
		if self.parent_category:
			return "(%s > %s) %s" % (self.parent_category.category_number, self.category_number, self.name)
		else:
			return "(%s) %s" % (self.category_number, self.name)


class IncidentCategory(models.Model):
	name = models.CharField(max_length=100)
	bale_subcategory = models.ForeignKey(BaleCategory)
	is_major = models.BooleanField(default=False)

	class Meta:
		verbose_name_plural = "Incident categories"

	def __unicode__(self):
		return self.name

# Core models ================================================================


class Incident(models.Model):
	date = models.DateTimeField(default=datetime.datetime.now, blank=True)
	is_starred = models.BooleanField(default=False)
	subject = models.CharField(max_length=256)
	description = models.TextField()
	category = models.ForeignKey(IncidentCategory)
	concerned_business_lines = models.ManyToManyField(BusinessLine, null=True, blank=True)
	main_business_lines = models.ManyToManyField(BusinessLine, related_name='incidents_affecting_main', null=True, blank=True)
	detection = models.ForeignKey(Label, limit_choices_to={'group__name': 'detection'}, related_name='detection_label')
	severity = models.IntegerField(choices=SEVERITY_CHOICES)
	is_incident = models.BooleanField(default=False)
	is_major = models.BooleanField(default=False)
	actor = models.ForeignKey(Label, limit_choices_to={'group__name': 'actor'}, related_name='actor_label', blank=True, null=True)
	plan = models.ForeignKey(Label, limit_choices_to={'group__name': 'plan'}, related_name='plan_label', blank=True, null=True)
	status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="Open")
	opened_by = models.ForeignKey(User)
	confidentiality = models.IntegerField(choices=CONFIDENTIALITY_LEVEL, default='1')

	def __unicode__(self):
		return self.subject

	def is_open(self):
		return self.get_last_action != "Closed"

	def close_timeout(self):
		self.status = 'C'
		self.save()

		c = Comments()
		c.comment = "Incident closed (timeout)"
		c.date = datetime.datetime.now()
		c.action = Label.objects.get(name='Closed', group__name='action')
		c.incident = self
		c.opened_by = User.objects.get(username='cert')
		c.save()

	def get_last_comment(self):
		return self.comments_set.order_by('-date')[0]

	def get_last_action(self):
		c = self.comments_set.order_by('-date')[0]

		action = "%s (%s)" % (c.action, c.date.strftime("%Y %d %b %H:%M:%S"))

		return action

	def concerns_business_line(self, bl_string):
		for bl in self.concerned_business_lines.all():
			if bl.name == bl_string:
				return True

			parent = bl.parent
			while parent:
				if parent.name == bl_string:
					return True
				parent = parent.parent

		return False

	def get_business_lines_names(self):
		return ", ".join([b.name for b in self.concerned_business_lines.all()])

	def refresh_main_business_lines(self):
		mainbls = set()
		for bl in self.concerned_business_lines.all():
			mainbls.add(bl.get_top_parent())
		self.main_business_lines = list(mainbls)

	def refresh_artifacts(self, data=""):
		if data == "":
			coms = self.comments_set.all()

			data = self.description
			for c in coms:
				data += "\n" + c.comment

		found_artifacts = artifacts.find(data)

		artifact_list = []
		for key in found_artifacts:
			for a in found_artifacts[key]:
				artifact_list.append((key, a))

		db_artifacts = Artifact.objects.filter(value__in=[a[1] for a in artifact_list])

		exist = []

		for a in db_artifacts:
			exist.append((a.type, a.value))
			if self not in a.incidents.all():
				a.incidents.add(self)

		new_artifacts = list(set(artifact_list) - set(exist))
		all_artifacts = list(set(artifact_list))

		for a in new_artifacts:
			new = Artifact(type=a[0], value=a[1])
			new.save()
			new.incidents.add(self)

		for a in all_artifacts:
			artifacts.after_save(a[0], a[1], self)

	class Meta:
		permissions = (
			('handle_incidents', 'Can handle incidents'),
			('view_statistics', 'Can view statistics'),
		)


class Comments(models.Model):
	date = models.DateTimeField(default=datetime.datetime.now, blank=True)
	comment = models.TextField()
	action = models.ForeignKey(Label, limit_choices_to={'group__name': 'action'}, related_name='action_label')
	incident = models.ForeignKey(Incident)
	opened_by = models.ForeignKey(User)

	def __unicode__(self):
		return u"Comment for incident %s" % self.incident.id


class Artifact(models.Model):
	type = models.CharField(max_length=20)
	value = models.CharField(max_length=200)
	incidents = models.ManyToManyField(Incident)

	def __unicode__(self):
		display = self.value
		if self.incidents.count() > 1:
			display += " (%s)" % self.incidents.count()
		return display


class Attribute(models.Model):
	name = models.CharField(max_length=50)
	value = models.CharField(max_length=200)
	incident = models.ForeignKey(Incident)

	def __unicode__(self):
		return "%s: %s" % (self.name, self.value)


class ValidAttribute(models.Model):
	name = models.CharField(max_length=50)
	unit = models.CharField(max_length=50, null=True, blank=True)
	description = models.CharField(max_length=500, null=True, blank=True)
	categories = models.ManyToManyField(IncidentCategory)

	def __unicode__(self):
		return self.name

# forms ===============================================================


class IncidentForm(ModelForm):

	def __init__(self, *args, **kwargs):
		super(ModelForm, self).__init__(*args, **kwargs)
		self.fields['subject'].error_messages['required'] = 'This field is required.'
		self.fields['category'].error_messages['required'] = 'This field is required.'
		self.fields['concerned_business_lines'].error_messages['required'] = 'This field is required.'
		self.fields['detection'].error_messages['required'] = 'This field is required.'

		self.fields['severity'].error_messages['required'] = 'This field is required.'
		self.fields['is_major'].error_messages['required'] = 'This field is required.'

		self.fields['is_major'].label = 'Major?'

	class Meta:
		model = Incident
		exclude = ('opened_by', 'main_business_lines', 'is_starred')


class CommentForm(ModelForm):

incidents/templates/events/_attributes.html
{% for attribute in attributes %}
<tr id='attribute-{{attribute.id}}' data-name='{{attribute.name}}' data-value='{{attribute.value}}' class='attribute-item'>
	<td class='head'>{{attribute.name}}</td>
	<td>
		{{attribute.value}}
	</td>
	<td>
		<form action="{% url 'incidents:delete_attribute' event.id attribute.id %}" method='POST' data-ajaxform data-action='remove' data-target='#attribute-{{attribute.id}}' data-hideifnone='#attributes' data-hideifnone-selector='.attribute-item'>
			{% csrf_token %}
			<button type="submit" class="btn btn-xs btn-link icon">
				<i class="glyphicon glyphicon-remove"></i>
			</button>
		</form>
	</td>
</tr>
{% endfor %}

incidents/templates/events/_comment.html
<tr id="comment_id_{{comment.id}}">
	<td class='comment-date'>{{ comment.date|date:"Y-m-d G:i" }}</td>
	<td>{{ comment.opened_by|default:"someone" }}</td>
	<td>{{ comment.comment|safe }}</td>
	<td>{{ comment.action }}</td>
	<td><a href='#' class='edit-comment' data-comment-id='{{comment.id}}'>
		<i class="glyphicon glyphicon-pencil" ></i>
	</a></td>
	<td><form id='delete_comment_{{comment.id}}' name='delete' action="{% url 'incidents:delete_comment' event.id comment.id %}" method='POST' data-ajaxform data-action='remove' data-target='#comment_id_{{comment.id}}'>
		{% csrf_token %}
		<button type='submit' class='btn btn-xs btn-link icon'><i class='glyphicon glyphicon-remove'></i></button>
	</form></td>
</tr>

incidents/templates/events/_form_errors.html
<span class='help-block'>
	{% for error in errors %}
		{{ error }}
	{% endfor %}
</span>

incidents/templates/events/column.html
<th>
	<a href='#' data-sort='{{ field }}'>{{ name }}
	{% if order_param == field %}
		<span class="glyphicon glyphicon-chevron-{% if asc == 'true' %}up{% else %}down{% endif %}"></i>
	{% endif %}
	</a>
</th>

incidents/templates/events/index-all.html
{% extends "base.html" %}

{% block custom_js %}
<script src='/static/custom_js/incident_display.js'></script>
{% endblock %}

{% block content %}
	{% if incident_view %}
		<div id='all_incidents' class='incident_display' data-url="{% url 'incidents:all' %}">
	{% else %}
		<div id='all_incidents' class='incident_display' data-url="{% url 'events:all' %}">
	{% endif %}
			Loading ...
		</div>
{% endblock %}

incidents/templates/events/new.html
{% extends "base.html" %}
{% load url from future %}
{% load add_css_class %}

{% block custom_css %}
<link href="/static/select/select2.css" rel="stylesheet"/>
<link href="/static/select/select2-bootstrap.css" rel="stylesheet"/>
<link href="/static/css/bootstrap-datetimepicker.min.css" rel="stylesheet"/>

{% endblock %}

{% block custom_js %}
<script src="/static/select/select2.min.js"></script>
<script>
$(document).ready(function() {
	$("select#id_concerned_business_lines").select2({ dropdownAutoWidth: true, width: '100%' });
	$("select#id_category").select2();
	$('select#id_status').select2({minimumResultsForSearch: -1, width: '90px'});
	$('select#id_detection').select2({minimumResultsForSearch: -1, width: '90px'});
	$('select#id_severity').select2({minimumResultsForSearch: -1, width: '90px'});
	$('select#id_actor').select2({minimumResultsForSearch: -1, width: '90px'});
	$('select#id_plan').select2({minimumResultsForSearch: -1, width: '90px'});
	$('select#id_confidentiality').select2({minimumResultsForSearch: -1, width: '90px'});
});
</script>

<script src='/static/js/bootstrap-datetimepicker.min.js'></script>

{% endblock %}


{% block content %}

	<div class="container-fluid">
		{% if not i %}
			<form action="{% url 'events:new' %}" method="post">
		{% else %}
			<form action="{% url 'incidents:edit' i.pk %}" method="post">
		{% endif %}

			<div class="row header">
				{% if not i %}
					<h1 class="col-sm-11">New event</h1>
				{% else %}
					<h1 class="col-sm-11">{% if i.is_incident %}Incident{%else%}Event{%endif%}: {{ i.subject }}</h1>
				{% endif %}
				<div class="col-sm-1">
					<button class="btn btn-primary" type="submit">Save</button>
				</div>
			</div>

			<div class="row">
				{% csrf_token %}

				<div class="col-sm-6">
					<fieldset>

						<legend>Summary</legend>
						{% if error_message %}
							<p class='text-error'>{{ error_message }}</p>
						{% endif %}

						<div class="row">
							<div class="col-sm-6 form-group{% if form.subject.errors%} has-error{%endif%}">
								<label for="id_subject">Subject</label>
								{{ form.subject|add_css_class:"form-control" }}
								{% include 'events/_form_errors.html' with errors=form.subject.errors %}
							</div>
							<div class="col-sm-6 form-group{% if form.concerned_business_lines.errors%} has-error{%endif%}">
								<label id="id_concerned_business_lines">Business Lines</label>
								{{ form.concerned_business_lines|add_css_class:"form-control" }}
								{% include 'events/_form_errors.html' with errors=form.concerned_business_lines.errors %}
							</div>
						</div>
						<div class="row">
							<div class="col-sm-6 form-group{% if form.category.errors%} has-error{%endif%}">
								<label id="id_category">Category</label>
								{{ form.category|add_css_class:"form-control" }}
								{% include 'events/_form_errors.html' with errors=form.category.errors %}
							</div>
							<div class="col-sm-2 form-group{% if form.status.errors%} has-error{%endif%}">
								<label id="id_status">Status</label>
								{{ form.status|add_css_class:"form-control" }}
								{% include 'events/_form_errors.html' with errors=form.status.errors %}
							</div>
							<div class="col-sm-2 form-group{% if form.detection.errors%} has-error{%endif%}">
								<label id="id_detection">Detection</label>
								{{ form.detection|add_css_class:"form-control" }}
								{% include 'events/_form_errors.html' with errors=form.detection.errors %}
							</div>
							<div class="col-sm-2 form-group{% if form.severity.errors%} has-error{%endif%}">
								<label id="id_severity">Severity</label>
								{{ form.severity|add_css_class:"form-control" }}
								{% include 'events/_form_errors.html' with errors=form.severity.errors %}
							</div>
						</div>
						<div class="row">
							<div class="col-sm-6 form-group{% if form.date.errors%} has-error{%endif%}">
								<label id="id_date">Date / Time</label>
								{{ form.date|add_css_class:"form-control datetime" }}
								{% include 'events/_form_errors.html' with errors=form.date.errors %}
							</div>
							<div class="col-sm-6 checkbox aligned-with-stack{% if form.is_incident.errors%} has-error{%endif%}">
								<label data-toggle='collapse' data-target='#incident_fields'>{{ form.is_incident }} Is an incident</label>
								{% include 'events/_form_errors.html' with errors=form.is_incident.errors %}
							</div>
						</div>
					</fieldset>
				</div>
				<div class="col-sm-6">
					<fieldset id="incident_fields" class='details collapse {% if form.is_incident.value %}in{%endif%}'>
						<legend>Incident details</legend>

						<div class="row">
							<div class="col-sm-2 form-group{% if form.actor.errors%} has-error{%endif%}">
								<label id="id_actor">Actor</label>
								{{ form.actor|add_css_class:"form-control" }}
								{% include 'events/_form_errors.html' with errors=form.actor.errors %}
							</div>
							<div class="col-sm-2 form-group{% if form.plan.errors%} has-error{%endif%}">
								<label id="id_plan">Plan</label>
								{{ form.plan|add_css_class:"form-control" }}
								{% include 'events/_form_errors.html' with errors=form.plan.errors %}
							</div>
							<div class="col-sm-2 form-group{% if form.confidentiality.errors%} has-error{%endif%}">
								<label id="id_confidentiality">Confidentiality</label>
								{{ form.confidentiality|add_css_class:"form-control" }}
								{% include 'events/_form_errors.html' with errors=form.confidentiality.errors %}
							</div>
							<div class="col-sm-6 checkbox aligned-with-stack{% if form.is_major.errors%} has-error{%endif%}">
								<label>{{ form.is_major }} Major incident</label>
								{% include 'events/_form_errors.html' with errors=form.is_major.errors %}
							</div>
						</div>
					</fieldset>
				</div>
			</div>
			<div class="row">
				<fieldset class="col-sm-12">
					<legend>Description</legend>
					{{ form.description|add_css_class:"form-control mce" }}
					{% include 'events/_form_errors.html' with errors=form.description.errors %}
				</fieldset>
				{{ form.non_field_errors }}
			</div>
			<button class="btn btn-primary" type="submit">Save</button>
		</form>
	</div>
{% endblock %}

incidents/templates/events/search.html
{% extends "base.html" %}
{% load fir_plugins %}

{% block header %}
<h4 class='search-results'>
	<i class='glyphicon glyphicon-search'></i>Search results for: <em>{{query_string}}</em>
</h4>
{% endblock %}

{% block custom_js %}
<script src='/static/custom_js/incident_display.js'></script>
{% endblock %}

{% block content %}
	<div id='all_incidents' class='incident_display' data-url="{% url 'search' %}" data-query='{{ query_string }}'>
		Loading ...
	</div>
{% endblock %}

incidents/templates/events/table.html
{% if incident_list %}
	<div class='incident_table' data-order-param='{{ order_param }}' data-asc='{{ asc }}'>
		<table class='table table-hover table-condensed'>
			<thead>
				<tr>
					{% include 'events/column.html' with name='Date' field='date' %}
					<th></th>
					{% include 'events/column.html' with name='Category' field='category' %}
					{% include 'events/column.html' with name='Subject' field='subject' %}
					<th>Business Lines</th>
					{% include 'events/column.html' with name='Severity' field='severity' %}
					{% include 'events/column.html' with name='Status' field='status' %}
					{% if incident_view %}
						{% include 'events/column.html' with name='Detection' field='detection' %}
						{% include 'events/column.html' with name='Leader' field='actor' %}
						{% include 'events/column.html' with name='Last Action' field='last_action' %}
						{% include 'events/column.html' with name='Plan' field='plan' %}
						{% include 'events/column.html' with name='Lvl' field='confidentiality' %}
					{% endif %}
					{% include 'events/column.html' with name='IH' field='opened_by' %}
					<th>Edit</th>
				</tr>
			</thead>
			<tbody>
				{% for incident in incident_list %}
					<tr class='{{ incident.status }}'>
						<td class='incident_date_column'>{{ incident.date|date:'Y-m-d' }}</td>
						<td>
							<a href="{% url 'ajax:toggle_star' incident.id %}" class='star'>
								{% if incident.is_starred %}
									<i class='glyphicon glyphicon-star star'></i>
								{% else %}
									<i class='glyphicon glyphicon-star-empty star'></i>
								{% endif %}
							</a>
						</td>
						<td>{{ incident.category }}</td>
						{% if incident.is_incident %}
							<td><a href="{% url 'incidents:details' incident.id %}">{{ incident.subject }}</a></td>
						{% else %}
							<td><a href="{% url 'events:details' incident.id %}">{{ incident.subject }}</a></td>
						{% endif %}
						<td>{{ incident.get_business_lines_names }}</td>
						<td><span class='badge threatcon-{{ incident.severity }}'>{{ incident.severity }}</span></td>
						<td>{{ incident.get_status_display }}</td>

						{% if incident_view %}
							<td>{{ incident.detection }}</td>
							<td>{{ incident.actor }}</td>
							<td>
								{% if incident.comments_set.count > 0%}
									{{ incident.get_last_comment.action }}
									<small class='relative-date'>
										({{ incident.get_last_comment.date|date:'Y-m-d G:i' }})
									</small>
								{% else %}
									None
								{%endif%}
							</td>
							<td>{{ incident.plan }}</td>
							<td>{{ incident.get_confidentiality_display }}</td>
						{% endif %}

						<td>{{ incident.opened_by }}</td>
						<td>
							<a href="{% url 'incidents:edit' incident.id %}"><span class='glyphicon glyphicon-pencil'></span></a>
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>

		{% if incident_list.paginator %}
			<div>
			    <span class="step-links">
			        {% if incident_list.has_previous %}
			        	<a href='#' class='paginate' data-page='{{ incident_list.previous_page_number }}'>
			        		<i class='glyphicon glyphicon-backward'></i> previous
			        	</a>
			        {% endif %}

			        <span class="current">
			            (page {{ incident_list.number }} of {{ incident_list.paginator.num_pages }})
			        </span>

			        {% if incident_list.has_next %}
			        	<a href='#' class='paginate' data-page='{{ incident_list.next_page_number }}'>
			        		next <i class='glyphicon glyphicon-forward'></i>
			        	</a>
			        {% endif %}
			    </span>
			</div>
		{% endif %}
	</div>
{% else %}
	<div class='nothing_to_show'>No incidents to show.</div>
{% endif %}