fir_alerting/urls.py
from django.conf.urls import patterns, url

from fir_alerting import views

urlpatterns = patterns('',
	url(r'^(?P<incident_id>\d+)/get_template/(?P<template_type>[\w-]+)/$', views.get_template, name='get_template'),
	url(r'^(?P<incident_id>\d+)/get_template/(?P<template_type>[\w-]+)/(?P<bl>[\d]+)/$', views.get_template, name='get_template'),
	url(r'^emailform/$', views.emailform, name='emailform'),
	url(r'^send_email/$', views.send_email, name='send_email'),
)

fir_todos/urls.py
from django.conf.urls import patterns, url

from fir_todos import views

urlpatterns = patterns('',
	url(r'^(?P<incident_id>\d+)/list/$', views.list, name='list'),
	url(r'^(?P<incident_id>\d+)/create/$', views.create, name='create'),
	url(r'^(?P<todo_id>\d+)/delete/$', views.delete, name='delete'),
	url(r'^(?P<todo_id>\d+)/toggle_status/$', views.toggle_status, name='toggle_status'),
	url(r'^tasks/$', views.dashboard, name='dashboard'),
)

fir_alerting/models.py
from django.db import models
from django import forms

from incidents.models import IncidentCategory, BusinessLine


class RecipientTemplate(models.Model):
	name = models.CharField(max_length=100)
	type = models.CharField(max_length=100)
	behalf = models.CharField(max_length=100)
	recipient_to = models.TextField()
	recipient_cc = models.TextField()
	recipient_bcc = models.TextField(null=True, blank=True)
	business_line = models.ForeignKey(BusinessLine, null=True, blank=True)

	def __unicode__(self):
		return self.name

	class Meta:
		db_table = 'incidents_recipienttemplate'


class CategoryTemplate(models.Model):
	name = models.CharField(max_length=100)
	type = models.CharField(max_length=100)
	body = models.TextField()
	subject = models.TextField()
	incident_category = models.ForeignKey(IncidentCategory)

	def __unicode__(self):
		return self.name

	class Meta:
		db_table = 'incidents_categorytemplate'


class EmailForm(forms.Form):
	behalf = forms.CharField()
	to = forms.CharField()
	cc = forms.CharField()
	bcc = forms.CharField()
	subject = forms.CharField()
	body = forms.CharField(widget=forms.Textarea)

fir_alerting/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from django.template import Context
from django.http import HttpResponse, HttpResponseBadRequest
from django.template import Template
from django.conf import settings
from json import dumps

from incidents.views import is_incident_handler
from incidents.models import Incident, BusinessLine

from fir_alerting.models import RecipientTemplate, CategoryTemplate, EmailForm


@login_required
@user_passes_test(is_incident_handler)
def emailform(request):
	email_form = EmailForm()

	return render(request, 'fir_alerting/emailform.html', {'form': email_form})


@login_required
@user_passes_test(is_incident_handler)
def get_template(request, incident_id, template_type, bl=None):
	i = get_object_or_404(Incident, pk=incident_id)

	try:
		cat_template = CategoryTemplate.objects.get(incident_category=i.category, type=template_type)
	except Exception, e:
		cat_template = None

	rec_template = None
	if not bl:
		q_bl = Q()
		bls = i.concerned_business_lines.all()
		for b in bls:
			q_bl |= Q(business_line=b)
		bl_name = i.get_business_lines_names()
	else:
		bl = get_object_or_404(BusinessLine, pk=bl)
		q_bl = Q(business_line=bl)
		bl_name = bl.name

	try:
		rec_template = RecipientTemplate.objects.get((q_bl | Q(business_line=None)) & Q(type=template_type))
	except Exception, e:
		print "Email template ERROR: ", e
		parents = list(set(i.concerned_business_lines.all()))

		while not rec_template and parents != [None]:
			try:
				parents = list(set([b.parent for b in parents]))
				q_parent = Q()
				for p in parents:
					q_parent |= Q(business_line=p)
				template = list(RecipientTemplate.objects.filter((q_parent | Q(business_line=None)) & Q(type=template_type)))
				if len(template) > 0:
					rec_template = template[0]
			except Exception as e:
				print "Email template ERROR 2: ", e
				break

	artifacts = {}
	for a in i.artifact_set.all():
		if a.type not in artifacts:
			artifacts[a.type] = []
		artifacts[a.type].append(a.value.replace('http://', "hxxp://").replace('https://', 'hxxps://'))

	c = Context({ 	'subject': i.subject.replace('http://', "hxxp://").replace('https://', 'hxxps://'),
					'bl': bl_name,
					'phishing_url': i.subject.replace('http://', "hxxp://").replace('https://', 'hxxps://'),
					'artifacts': artifacts,
				})

	response = {
					'behalf': rec_template.behalf if rec_template else "",
					'to': rec_template.recipient_to if rec_template else "",
					'cc': rec_template.recipient_cc if rec_template else "",
					'bcc': rec_template.recipient_bcc if rec_template else "",
					'subject': Template(cat_template.subject).render(c) if cat_template else "",
					'body': Template(cat_template.body).render(c) if cat_template else "",
					'bl': bl_name,
				}

	return HttpResponse(dumps(response), content_type="application/json")


@login_required
@user_passes_test(is_incident_handler)
def send_email(request):
	if request.method == 'POST':
		try:
			from django.core.mail import EmailMultiAlternatives
			behalf = request.POST['behalf']
			to = request.POST['to']
			cc = request.POST['cc']
			bcc = request.POST['bcc']

			subject = request.POST['subject']
			body = request.POST['body']

			if hasattr(settings, 'REPLY_TO'):
				reply_to = {'Reply-To': settings.REPLY_TO, 'Return-Path': settings.REPLY_TO}
			else:
				reply_to = {}

			e = EmailMultiAlternatives(	subject=subject,
										from_email=behalf,
										to=to.split(';'),
										cc=cc.split(';'),
										bcc=bcc.split(';'),
										headers=reply_to
										)
			e.attach_alternative(body, 'text/html')
			e.content_subtype = 'html'
			e.send()

			return HttpResponse(dumps({'status': 'ok'}), content_type="application/json")

		except Exception, e:
			return HttpResponse(dumps({'status': 'ko', 'error': str(e)}), content_type="application/json")

	return HttpResponseBadRequest(dumps({'status': 'ko'}), content_type="application/json")

fir_alerting/templates/fir_alerting/emailform.html
<div id="sendEmail" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="sendEmailLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 id="sendEmailLabel" class="modal-title">Send email</h3>
			</div>

			<form id="email_form" action="{% url 'alerting:send_email' %}" method="POST" class='form-horizontal'>
				<div class="modal-body">
					{% csrf_token %}
					<div class='form-group nomargin'>
						<label for="id_behalf" class="col-sm-1 text-right">From:</label>
						<div class='col-sm-11'>
							{{ form.behalf }}
						</div>
					</div>
					<div class='form-group nomargin'>
						<label for="id_to" class="col-sm-1 text-right">To:</label>
						<div class='col-sm-11'>
							{{ form.to }}
						</div>
					</div>
					<div class='form-group nomargin'>
						<label for="id_cc" class="col-sm-1 text-right">CC:</label>
						<div class='col-sm-11'>
							{{ form.cc }}
						</div>
					</div>
					<div class='form-group nomargin'>
						<label for="id_bcc" class="col-sm-1 text-right">BCC:</label>
						<div class='col-sm-11'>
							{{ form.bcc }}
						</div>
					</div>
					<div class='form-group'>
						<label for="id_subject" class="col-sm-1 text-right">Subject</label>
						<div class='col-sm-11'>
							{{ form.subject|safe }}
						</div>
					</div>
					<div class='form-group'>
						<label for="id_body" class="col-sm-1 text-right">Body</label>
						<div class='col-sm-11'>
							{{ form.body|safe }}
						</div>
					</div>
				</div>
			</form>

			<div class="modal-footer">
				<button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Close</button>
				<button data-sent-text="Message sent" data-loading-text="Sending..." id='send_email' class="btn btn-primary">Send email</button>
			</div>
		</div>
	</div>
</div>